chore(deps): Bump github.com/vektah/gqlparser/v2 from 2.5.10 to 2.5.11 (#29)
Bumps
[github.com/vektah/gqlparser/v2](https://github.com/vektah/gqlparser)
from 2.5.10 to 2.5.11.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/vektah/gqlparser/releases">github.com/vektah/gqlparser/v2's
releases</a>.</em></p>
<blockquote>
<h2>v2.5.11</h2>
<h2>What's Changed</h2>
<ul>
<li>Bump get-func-name from 2.0.0 to 2.0.2 in /validator/imported by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/vektah/gqlparser/pull/284">vektah/gqlparser#284</a></li>
<li>Bump <code>@​babel/traverse</code> from 7.22.6 to 7.23.2 in
/validator/imported by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/vektah/gqlparser/pull/285">vektah/gqlparser#285</a></li>
<li>Fix description formatting (possible &quot; character) by <a
href="https://github.com/blmhemu"><code>@​blmhemu</code></a> in <a
href="https://redirect.github.com/vektah/gqlparser/pull/289">vektah/gqlparser#289</a></li>
<li>gqlerror: implement List.Unwrap by <a
href="https://github.com/emersion"><code>@​emersion</code></a> in <a
href="https://redirect.github.com/vektah/gqlparser/pull/290">vektah/gqlparser#290</a></li>
</ul>
<h2>New Contributors</h2>
<ul>
<li><a href="https://github.com/blmhemu"><code>@​blmhemu</code></a> made
their first contribution in <a
href="https://redirect.github.com/vektah/gqlparser/pull/289">vektah/gqlparser#289</a></li>
<li><a href="https://github.com/emersion"><code>@​emersion</code></a>
made their first contribution in <a
href="https://redirect.github.com/vektah/gqlparser/pull/290">vektah/gqlparser#290</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/vektah/gqlparser/compare/v2.5.10...v2.5.11">https://github.com/vektah/gqlparser/compare/v2.5.10...v2.5.11</a></p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/vektah/gqlparser/commit/591c98bb315b8c840f94afbaa566dc6770f9d98c"><code>591c98b</code></a>
gqlerror: implement List.Unwrap (<a
href="https://redirect.github.com/vektah/gqlparser/issues/290">#290</a>)</li>
<li><a
href="https://github.com/vektah/gqlparser/commit/a9429543316787728c603716962416032c43f2c1"><code>a942954</code></a>
Fix description (<a
href="https://redirect.github.com/vektah/gqlparser/issues/289">#289</a>)</li>
<li><a
href="https://github.com/vektah/gqlparser/commit/bf1736ae2956d714094fd06e76c43888fb598867"><code>bf1736a</code></a>
Bump <code>@​babel/traverse</code> from 7.22.6 to 7.23.2 in
/validator/imported (<a
href="https://redirect.github.com/vektah/gqlparser/issues/285">#285</a>)</li>
<li><a
href="https://github.com/vektah/gqlparser/commit/e5a1b674bc5565102c9af33e54fb2bbe16040fa8"><code>e5a1b67</code></a>
Bump get-func-name from 2.0.0 to 2.0.2 in /validator/imported (<a
href="https://redirect.github.com/vektah/gqlparser/issues/284">#284</a>)</li>
<li>See full diff in <a
href="https://github.com/vektah/gqlparser/compare/v2.5.10...v2.5.11">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=github.com/vektah/gqlparser/v2&package-manager=go_modules&previous-version=2.5.10&new-version=2.5.11)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>